### ISSUE TITLE
ARC semantics issue & ARC restriction

### ISSUE THREAD

**Issue by diwsky** [adjust/flutter_sdk#62]
![image](https://user-images.githubusercontent.com/40056095/135037210-32255c56-cc26-4281-9467-f05b2ab52fc2.png)

Hi folks,

I got an issue when building app for IOS 15.0
I was using both `adjust_sdk: ^4.29.0` and `adjust_sdk: ^4.29.1` but this issue still remains.

Here is my environment:
Flutter version: 2.5.1
IOS version: 15.0
Simulator version: Version 13.0 (970), Simulator kit 612, CoreSimulator 776.3
Xcode: Version 13.0 (13A233)
MacOS: Big Sur 11.6
Mac: MBP 13-inch, M1 chip

**Comment by uerceg** [comment]
Hi @diwsky,

Did you `pod update` dependencies in your iOS app? Latest Flutter SDK version should be pulling native iOS SDK version where this has been addressed.

Give it a shot and let us know if it worked for you.

Cheers

**Comment by brenoasm** [comment]
I am having the same problem. IOS 15, Flutter 2.5.1 and Adjust ^4.29.0

**Comment by uerceg** [comment]
Hi @brenoasm,

Same question as above - what's the native iOS SDK version in your iOS app project? Did you update your pods?

**Comment by brenoasm** [comment]
I did run pod update, pod install --repo-update and no success. Tried to run on IOS 14.4 and my problem persists.

<img width="243" alt="Captura de Tela 2021-09-28 às 11 44 55" src="https://user-images.githubusercontent.com/25211056/135110294-feef1a44-1ab8-49e1-a476-ae67e6db3285.png">

**Comment by uerceg** [comment]
Can you please give latest Flutter SDK version a shot (v4.29.1) because that's the version where Xcode 13 compatibility issue has been addressed?

**Comment by brenoasm** [comment]
@uerceg I'll try. Thanks for the quick responses.

**Comment by brenoasm** [comment]
Just worked... Thanks a lot @uerceg

**Comment by diwsky** [comment]
Hi @uerceg, previously I tried `pod update` but seems no luck. 

But then I tried to `pod install Adjust ` and then the adjust native ios version change to 4.29.6, and then the build finished. Is it okay having different sdk version between native and the pubspec?

**Comment by uerceg** [comment]
Hey, glad to hear that it worked.

Version wise, yes, that's expected and how things work with each non native SDK we build. Every Flutter SDK version we release contains under the hood native iOS and Android SDK versions which are latest in the moment of when we make the release. Not necessarily aligned. Each SDK (native and non native) has its own versioning path, so having versions not aligned is perfectly expected.

If you check [CHANGELOG](https://github.com/adjust/flutter_sdk/blob/master/CHANGELOG.md), you can see in there that for every Flutter SDK release we make we are mentioning what are underlying native iOS and Android versions which are part of that particular Flutter SDK release.

**Comment by uerceg** [comment]
In case any assistance is still needed, feel free to comment / reopen.
